quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=postgres
quarkus.datasource.password=admin123

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres

quarkus.http.limits.max-body-size=50M
quarkus.http.body.handle-file-uploads=true

quarkus.index-dependency.model.group-id=com.ffb
quarkus.index-dependency.model.artifact-id=model
quarkus.hibernate-orm.packages=com.ffb.model

# Verify incoming JWTs
mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=https://your-app.example

# Sign JWTs you create in /auth/login
smallrye.jwt.sign.key.location=classpath:privateKey.pem

# Read JWT from a cookie
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=access_token

# Optional: also accept Authorization header if someone uses it (useful for Postman)
smallrye.jwt.always-check-authorization=true

quarkus.swagger-ui.with-credentials=true