quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=postgres
quarkus.datasource.password=admin123

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres

ffb.image.path={appDir}/images

quarkus.http.limits.max-body-size=50M
quarkus.http.body.handle-file-uploads=true

quarkus.index-dependency.model.group-id=com.ffb
quarkus.index-dependency.model.artifact-id=model
quarkus.hibernate-orm.packages=com.ffb.model

