# Application Specific Custom Config
foodcourt.preparation.speed=5
foodcourt.preparation.time=600
foodcourt.simmulation.speed=300
account.initial.credit=1000
order.extra.price=2.0

app.endpoint-counter.file=endpoint-counts.json
app.endpoint-counter.flush-seconds=30

# show SQL
#quarkus.hibernate-orm.log.sql=true
#quarkus.hibernate-orm.log.format-sql=true
#quarkus.hibernate-orm.log.bind-parameters=true

quarkus.http.root-path=/ffb
quarkus.http.non-application-root-path=${quarkus.http.root-path}

# Root Log Config
quarkus.log.min-level=TRACE
quarkus.log.level=TRACE

# Console Log Config
quarkus.log.console.enabled=true
quarkus.log.console.level=INFO

# App File Log Configuration
quarkus.log.handler.file.APP.enabled=true
quarkus.log.handler.file.APP.path=Logs/App/app.log
quarkus.log.handler.file.APP.level=TRACE
quarkus.log.handler.file.APP.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.handler.file.APP.rotation.max-file-size=10M
quarkus.log.handler.file.APP.rotation.max-backup-index=10
# App Handler Attachment
quarkus.log.category."com.ffb".level=TRACE
quarkus.log.category."com.ffb".handlers=APP
quarkus.log.category."com.ffb".use-parent-handlers=true

# Quarkus File Log Configuration
quarkus.log.handler.file.QUARKUS.enabled=true
quarkus.log.handler.file.QUARKUS.path=Logs/Quarkus/quarkus.log
quarkus.log.handler.file.QUARKUS.level=INFO
quarkus.log.handler.file.QUARKUS.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.handler.file.QUARKUS.rotation.max-file-size=10M
quarkus.log.handler.file.QUARKUS.rotation.max-backup-index=10

# Quarkus Handler Attachment
quarkus.log.category."io.quarkus".level=INFO
quarkus.log.category."io.quarkus".handlers=QUARKUS
quarkus.log.category."io.quarkus".use-parent-handlers=true
# Smallrye Handler Attachment
quarkus.log.category."io.smallrye".level=INFO
quarkus.log.category."io.smallrye".handlers=QUARKUS
quarkus.log.category."io.smallrye".use-parent-handlers=true
# Hibernate Handler Attachment
quarkus.log.category."org.hibernate".level=INFO
quarkus.log.category."org.hibernate".handlers=QUARKUS
quarkus.log.category."org.hibernate".use-parent-handlers=true
# JBoss Handler Attachment
quarkus.log.category."org.jboss".level=INFO
quarkus.log.category."org.jboss".handlers=QUARKUS
quarkus.log.category."org.jboss".use-parent-handlers=true

# Cors Configuration
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000,http://localhost:8080
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,X-Requested-With,Accept,Origin

# Endpoints Permission Configuration
quarkus.http.auth.permission.public.paths=/ffb/health/*,/ffb/openapi,/ffb/swagger-ui/*,/ffb/dev-ui/*,/ffb/master/*,/ffb/account/login,/ffb/account/register
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# Verify incoming JWTs
mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=festival_food_app
smallrye.jwt.sign.key.location=classpath:privateKey.pem

# Read JWT from a cookie
#mp.jwt.token.header=Cookie
#mp.jwt.token.cookie=access_token

# Accept Authorization header (for Postman)
smallrye.jwt.always-check-authorization=true

# Create Swagger UI with Credentials Component
quarkus.swagger-ui.with-credentials=true

# Configure Upload and Upload Size for Files (Images)
quarkus.http.body.handle-file-uploads=true
quarkus.http.limits.max-body-size=50M

# Make Quarkus Swagger UI and Dev UI available on other Machines
quarkus.http.host=0.0.0.0
quarkus.http.port=8080

# Configure Hibernate for the different Schemas
quarkus.hibernate-orm.datasource=main
quarkus.hibernate-orm.packages=com.ffb.model.db.object
quarkus.hibernate-orm.schema-management.strategy=update

quarkus.hibernate-orm."virtual".datasource=main
quarkus.hibernate-orm."virtual".packages=com.ffb.model.db.view
quarkus.hibernate-orm."virtual".database.generation=none

# Database Configuration
quarkus.datasource."main".db-kind=postgresql 
quarkus.datasource."main".username=postgres
quarkus.datasource."main".password=admin123
quarkus.datasource."main".jdbc.url=jdbc:postgresql://localhost:5432/postgres