export const STORAGE_KEYS = {
  session: "ffb.session.v1",
  cart: "ffb.cart.v1",
  credit: "ffb.credit.v1",
  foodCourts: "ffb.foodCourts.v1",
  foodCourtImages: "ffb.foodCourtImages.v1",
  ownFoodCourtId: "ffb.ownFoodCourtId.v1",
  orders: "ffb.orders.v1",
  orderHistory: "ffb.orderHistory.v1",
  notifications: "ffb.notifications.v1",
  products: "ffb.products.v1",
  productAssignments: "ffb.productAssignments.v1",
  productFoodCourtMap: "ffb.productFoodCourtMap.v1",
  initialImport: "ffb.initialImport.v1",
} as const;
